import Head from "next/head";
import Characters from "../components/Characters";
import Navbar from "../components/Navbar";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Starwars App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Characters props={data} />
    </>
  );
}

export async function getStaticProps(context) {
  const res = await fetch("https://akabab.github.io/starwars-api/api/all.json");
  const data = await res.json();
  console.log("data--->", data);
  return {
    props: { data },
  };
}
